### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by lulumagic7** [venkatajonnakuti/PolyAMiner-Bulk#2]
Hi,
I got the error when I tried to run the polyAMiner-Bulk:
 
FileNotFoundError: [Errno 2] No such file or directory: '/data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/output/pred_results.npy'

Could you please help me fix it?
 

I use module anaconda3 R/4.2.1
my "pip list" output is: 

absl-py                       1.4.0
alabaster                     0.7.13
argcomplete                   2.0.0
argh                          0.27.2
asciitree                     0.3.3
attrs                         22.2.0
Babel                         2.11.0
blosc2                        2.0.0
boto3                         1.26.70
botocore                      1.29.70
brotlipy                      0.7.0
cachetools                    5.3.0
certifi                       2022.12.7
cffi                          1.15.1
charset-normalizer            2.1.1
click                         8.1.3
contourpy                     1.0.7
cryptography                  39.0.1
cycler                        0.11.0
Cython                        0.29.33
deepTools                     3.5.1
deeptoolsintervals            0.1.9
dill                          0.3.6
docutils                      0.19
exceptiongroup                1.1.0
filelock                      3.9.0
fonttools                     4.38.0
future                        0.18.3
google-auth                   2.16.0
google-auth-oauthlib          0.4.6
grpcio                        1.51.1
gtfparse                      1.2.1
h5py                          3.8.0
huggingface-hub               0.12.1
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.0.0
importlib-resources           5.10.2
iniconfig                     2.0.0
intervaltree                  3.1.0
Jinja2                        3.1.2
jmespath                      1.0.1
joblib                        1.2.0
kiwisolver                    1.4.4
Markdown                      3.4.1
MarkupSafe                    2.1.2
matplotlib                    3.7.0
msgpack                       1.0.4
multiprocess                  0.70.14
munkres                       1.1.4
numexpr                       2.8.4
numpy                         1.24.2
numpydoc                      1.5.0
oauthlib                      3.2.2
packaging                     23.0
pandas                        1.5.3
patsy                         0.5.3
Pillow                        9.4.0
pip                           23.0
plotly                        5.13.0
pluggy                        1.0.0
protobuf                      4.21.12
py-cpuinfo                    9.0.0
py2bit                        0.3.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybedtools                    0.9.0
pyBigWig                      0.3.18
pycparser                     2.21
pyfaidx                       0.7.1
pyfasta                       0.5.2
Pygments                      2.14.0
pyOpenSSL                     23.0.0
pyparsing                     3.0.9
pysam                         0.20.0
PySocks                       1.7.1
pytest                        7.2.1
python-dateutil               2.8.2
pytz                          2022.7.1
pytz-deprecation-shim         0.1.0.post0
PyYAML                        6.0
regex                         2022.10.31
requests                      2.28.2
requests-oauthlib             1.3.1
rpy2                          3.5.8
rsa                           4.9
s3transfer                    0.6.0
sacremoses                    0.0.53
scikit-learn                  1.2.1
scipy                         1.10.0
seaborn                       0.12.2
sentencepiece                 0.1.97
setuptools                    67.1.0
simplejson                    3.18.3
six                           1.16.0
sklearn                       0.0.post1
snowballstemmer               2.2.0
sortedcontainers              2.4.0
Sphinx                        6.1.3
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
statsmodels                   0.13.5
tables                        3.8.0
tenacity                      8.2.1
tensorboard                   2.12.0
tensorboard-data-server       0.7.0
tensorboard-plugin-wit        1.8.1
threadpoolctl                 3.1.0
tokenizers                    0.5.0
tomli                         2.0.1
toolz                         0.12.0
torch                         1.11.0
torchaudio                    0.11.0
torchvision                   0.12.0
tqdm                          4.64.1
transformers                  2.5.0       /scratch/colu3p/poly/PolyAMiner-Bulk/l                                             ib/DNABERT/src
typing_extensions             4.4.0
tzdata                        2022.7
tzlocal                       4.2
unicodedata2                  15.0.0
urllib3                       1.26.14
uuid                          1.30
Werkzeug                      2.2.2
wheel                         0.38.4
zipp                          3.13.0

My "conda list" output is:
# packages in environment at /usr/local/anaconda3-2020/envs/cpasbert:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   1.4.0                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
argcomplete               2.0.0                    pypi_0    pypi
argh                      0.27.2                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
babel                     2.11.0                   pypi_0    pypi
bedtools                  2.30.0               h468198e_3    bioconda
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0            16_linux64_mkl    conda-forge
blosc2                    2.0.0                    pypi_0    pypi
boto3                     1.26.70                  pypi_0    pypi
botocore                  1.29.70                  pypi_0    pypi
brotli                    1.0.9                h5eee18b_7    anaconda
brotli-bin                1.0.9                h5eee18b_7    anaconda
brotlipy                  0.7.0           py39hb9d737c_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2023.01.10           h06a4308_0    anaconda
cachetools                5.3.0                    pypi_0    pypi
certifi                   2022.12.7        py39h06a4308_0    anaconda
cffi                      1.15.1           py39he91dace_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3                    pypi_0    pypi
contourpy                 1.0.7            py39h4b4f3f3_0    conda-forge
cryptography              39.0.1           py39h079d5ae_0    conda-forge
cudatoolkit               10.0.130            h8c5a6a4_11    conda-forge
curl                      7.87.0               hdc1c0ab_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0    anaconda
cython                    0.29.33                  pypi_0    pypi
deeptools                 3.5.1                    pypi_0    pypi
deeptoolsintervals        0.1.9                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
docutils                  0.19                     pypi_0    pypi
exceptiongroup            1.1.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.9.0                    pypi_0    pypi
fonttools                 4.38.0           py39hb9d737c_1    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
future                    0.18.3                   pypi_0    pypi
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
google-auth               2.16.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.51.1                   pypi_0    pypi
gtfparse                  1.2.1              pyh864c0ab_0    bioconda
h5py                      3.8.0                    pypi_0    pypi
huggingface-hub           0.12.1                   pypi_0    pypi
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
importlib-resources       5.10.2                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jpeg                      9e                   h0b41bf4_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py39h6a678d5_0    anaconda
krb5                      1.20.1               h81ceb04_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.14                 hfd0df8a_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0            16_linux64_mkl    conda-forge
libbrotlicommon           1.0.9                h5eee18b_7    anaconda
libbrotlidec              1.0.9                h5eee18b_7    anaconda
libbrotlienc              1.0.9                h5eee18b_7    anaconda
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libcurl                   7.87.0               hdc1c0ab_0    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libedit                   3.1.20221030         h5eee18b_0
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libhwloc                  2.8.0                h32351e8_1    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblapacke                3.9.0            16_linux64_mkl    conda-forge
libnghttp2                1.51.0               hff17c54_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               15.0.7               h0cdce71_0    conda-forge
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.0                    pypi_0    pypi
matplotlib-base           3.6.3            py39he190548_0    conda-forge
mkl                       2022.1.0           h84fe81f_915    conda-forge
mkl-devel                 2022.1.0           ha770c72_916    conda-forge
mkl-include               2022.1.0           h84fe81f_915    conda-forge
msgpack                   1.0.4                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
munkres                   1.1.4                      py_0    anaconda
ncurses                   6.3                  h27087fc_1    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
numexpr                   2.8.4                    pypi_0    pypi
numpy                     1.24.2           py39h7360e5f_0    conda-forge
numpydoc                  1.5.0                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.0.8                h0b41bf4_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3            py39h2ad29b5_0    conda-forge
patsy                     0.5.3                    pypi_0    pypi
pillow                    9.4.0            py39h2320bf1_1    conda-forge
pip                       23.0               pyhd8ed1ab_0    conda-forge
plotly                    5.13.0                   pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
protobuf                  4.21.12                  pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
py-cpuinfo                9.0.0                    pypi_0    pypi
py2bit                    0.3.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pybedtools                0.9.0                    pypi_0    pypi
pybigwig                  0.3.18                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyfaidx                   0.7.1                    pypi_0    pypi
pyfasta                   0.5.2                      py_1    bioconda
pygments                  2.14.0                   pypi_0    pypi
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9            py39h06a4308_0    anaconda
pysam                     0.20.0                   pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.2.1                    pypi_0    pypi
python                    3.9.16          h2782a2a_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pytorch                   1.11.0              py3.9_cpu_0    pytorch
pytorch-mutex             1.0                         cpu    pytorch
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
regex                     2022.10.31               pypi_0    pypi
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
s3transfer                0.6.0                    pypi_0    pypi
sacremoses                0.0.53                   pypi_0    pypi
samtools                  1.6                  h3f2fef4_8    bioconda
scikit-learn              1.2.1                    pypi_0    pypi
scipy                     1.10.0                   pypi_0    pypi
seaborn                   0.12.2           py39h06a4308_0    anaconda
sentencepiece             0.1.97                   pypi_0    pypi
setuptools                67.1.0             pyhd8ed1ab_0    conda-forge
simplejson                3.18.3                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
sphinx                    6.1.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
statsmodels               0.13.5                   pypi_0    pypi
subread                   2.0.3                h7132678_1    bioconda
tables                    3.8.0                    pypi_0    pypi
tbb                       2021.7.0             h924138e_1    conda-forge
tenacity                  8.2.1                    pypi_0    pypi
tensorboard               2.12.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tokenizers                0.5.0                    pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torchaudio                0.11.0                 py39_cpu    pytorch
torchvision               0.12.0                 py39_cpu    pytorch
tqdm                      4.64.1                   pypi_0    pypi
transformers              2.5.0                     dev_0    <develop>
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
unicodedata2              15.0.0           py39h5eee18b_0    anaconda
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.13.0                   pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge

my python version is Python 3.9.16

my running script is:
python3 /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/PolyAMiner-Bulk-master/PolyA-miner.py -mode bam \ -fasta /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/Index_Files/Index_Files/Human/GRCh38.primary_assembly.genome.fa \ -gtf /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/Index_Files/Index_Files/Human/gencode.v33.primary_assembly.annotation.gtf \ -p 20 -a 0.65 -outPrefix 3UTROnly -expNovel 1 -s 2 \ -o /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/output \ -c1 /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluU6_3.sorted.bam, \ /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluU4_3.sorted.bam \ -c2 /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluF2_6.sorted.bam, \ /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluF1_6.sorted.bam \ -ignore UTR5,CDS,Intron,UN -apriori_annotations -modelOrganism human \ -visualizeTopNum 10 -visualizeCondition1Name Control -visualizeCondition2Name FXS

Thanks so much!

Best,

Lu Lu

**Comment by venkatajonnakuti** [comment]
Hi Lu,

Thank you for using PolyAMiner-Bulk! Could you retry running this command instead?

I removed the spaces from the comma-separated file list for the c1 and c2 parameters from your running script. 

python3 /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/PolyAMiner-Bulk-master/PolyA-miner.py -mode bam \ -fasta /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/Index_Files/Index_Files/Human/GRCh38.primary_assembly.genome.fa \ -gtf /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/Index_Files/Index_Files/Human/gencode.v33.primary_assembly.annotation.gtf \ -p 20 -a 0.65 -outPrefix 3UTROnly -expNovel 1 -s 2 \ -o /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/output \ -c1 /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluU6_3.sorted.bam,\/data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluU4_3.sorted.bam \ -c2 /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluF2_6.sorted.bam,\/data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluF1_6.sorted.bam \ -ignore UTR5,CDS,Intron,UN -apriori_annotations -modelOrganism human \ -visualizeTopNum 10 -visualizeCondition1Name Control -visualizeCondition2Name FXS

**Comment by lulumagic7** [comment]
Sorry Venkata,

I got this error,

![image](https://user-images.githubusercontent.com/116028527/223776288-8167c711-1437-4129-8288-e01c06c11c89.png)
(cpasbert) [lulvg4@bmi-r740-03 test]$ python3 /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/PolyAMiner-Bulk-master/PolyA-miner.py -mode bam \ -fasta /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/Index_Files/Index_Files/Human/GRCh38.primary_assembly.genome.fa \ -gtf /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/Index_Files/Index_Files/Human/gencode.v33.primary_assembly.annotation.gtf \ -p 20 -a 0.65 -outPrefix 3UTROnly -expNovel 1 -s 2 \ -o /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/output \ -c1 /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluU6_3.sorted.bam,/data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluU4_3.sorted.bam \ -c2 /data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluF2_6.sorted.bam,/data/epifluidlab/lulu/rnaseq_1st/6_splicing_polyaminer/test/bam/GluF1_6.sorted.bam \ -ignore UTR5,CDS,Intron,UN -apriori_annotations -modelOrganism human \ -visualizeTopNum 10 -visualizeCondition1Name Control -visualizeCondition2Name FXS
INFO:transformers.file_utils:PyTorch version 1.11.0 available.
usage: PolyA-miner.py [-h] -mode {bam,fastq} [-d D] [-o O] -c1 C1 [C1 ...] -c2 C2 [C2 ...] [-s {0,1,2}] [-index INDEX]
                      -fasta FASTA -gtf GTF [-pa PA] [-apriori_annotations] [-paired] [-verboseLogging] [-verbosePrinting]
                      [-noDEGAnalyzer] [-umi UMI] [-ignore IGNORE [IGNORE ...]] [-apaBlock APABLOCK] [-mdapa MDAPA]
                      [-md MD] [-anchor ANCHOR] [-softclippedNumReads SOFTCLIPPEDNUMREADS]
                      [-softclippedNumSamples SOFTCLIPPEDNUMSAMPLES] [-slopDistanceParameter SLOPDISTANCEPARAMETER]
                      [-clusterParameter CLUSTERPARAMETER] [-cluster_onGenes {all,3utr,none}]
                      [-cluster_onPAsites {all,3utr,none}] [-DEG {all,3utr,none}] [-pa_usage {all,filtered,none}]
                      [-expNovel {1,0}] [-novel_d NOVEL_D] [-p P] [-ip_d IP_D] [-ip_u IP_U] [-a A] [-pa_p PA_P]
                      [-pa_a PA_A] [-pa_m PA_M] [-gene_min GENE_MIN] [-apa_min APA_MIN] [-batchCorrection BATCHCORRECTION]
                      [-modelOrganism MODELORGANISM] [-visualizeTopNum VISUALIZETOPNUM]
                      [-visualizeCondition1Name VISUALIZECONDITION1NAME] [-visualizeCondition2Name VISUALIZECONDITION2NAME]
                      [-visualizeCondition1NameHeatmap VISUALIZECONDITION1NAMEHEATMAP]
                      [-visualizeCondition2NameHeatmap VISUALIZECONDITION2NAMEHEATMAP] [-outPrefix OUTPREFIX]
PolyA-miner.py: error: the following arguments are required: -c1, -c2, -fasta, -gtf

**Comment by venkatajonnakuti** [comment]
Does the test script on the demo data work for you? 

Link to test script and demo data:
https://github.com/venkatajonnakuti/PolyAMiner-Bulk/tree/master/Demo

**Comment by lulumagic7** [comment]
I tried last week, also couldn't work for me.

**Comment by lulumagic7** [comment]
> Does the test script on the demo data work for you?
> 
> Link to test script and demo data: https://github.com/venkatajonnakuti/PolyAMiner-Bulk/tree/master/Demo

Wait, I just tried again, it is running now! the demo data.

**Comment by lulumagic7** [comment]
![image](https://user-images.githubusercontent.com/116028527/223824139-67337d33-1f32-40dc-8362-20f16c32a890.png)
The demo data got another error.

**Comment by venkatajonnakuti** [comment]
It looks like that there is a featureCounts version discrepancy. PolyAMiner-Bulk was meant to be used w/ FeatureCounts v 2.0.0. Subsequent versions introduce a new parameter that must be added for paired end read data. 

I will fix this bug so that PolyAMiner-Bulk is FeatureCounts version agnostic. Will post another update shortly.

**Comment by lulumagic7** [comment]
> It looks like that there is a featureCounts version discrepancy. PolyAMiner-Bulk was meant to be used w/ FeatureCounts v 2.0.0. Subsequent versions introduce a new parameter that must be added for paired end read data.
> 
> I will fix this bug so that PolyAMiner-Bulk is FeatureCounts version agnostic. Will post another update shortly.

Yes, it works for me now! thanks so much!
